[ClassVersion("1.0.0.0"), FriendlyName("RefreshRegistryPolicy")]
class MSFT_RefreshRegistryPolicy : OMI_BaseResource
{
    [Key, Description("A name to serve as the key property. It is not used during configuration.")] String Name;
    [Read, Description("Returns the value of the GPRegistryPolicy key indicating a group policy refresh is needed.")] String RefreshRequiredKey;
    [Read, Description("Returns the path of the RefreshRequired property indicating a group policy refresh is needed.")] String Path;
};
