[ClassVersion("1.0.0.0"), FriendlyName("RefreshRegistryPolicy")]
class MSFT_RefreshRegistryPolicy : OMI_BaseResource
{
    [Key, Description("A name to serve as the key property. It is not used during configuration.")] String Name;
    [Read, Description("Specifies the regsitry key path indicating a group policy refresh is needed.")] String RefreshRequiredKey;
    [Read, Description("Specifies the value of the RefreshRequired key indicating a group policy refresh is needed.")] String RefreshRequiredKeyValue;
};
